### ISSUE TITLE
CircleCI Build Status box showing up blank

### ISSUE THREAD

**Issue by arowla** [18F/github-dashing#28]
This is since the merge in #27, maybe related?

**Comment by arowla** [comment]
cc @monfresh

**Comment by arowla** [comment]
It's back up. Nevermind!

**Comment by monfresh** [comment]
Yeah, the job is scheduled to kick off 5 minutes after a deploy (I stagger each widget to reduce API calls and memory usage), and I posted the link to the dashboard too soon :)
